meta_product_name: "Trip Buddy"
meta_title: "Trip Buddy - Your Best Companion"
meta_description: "Trip Buddy is the right companion for every adventurer who wants to find the best spots available in mauritius. We have frequent updates of our events and locations so as to make you feel confident in your journey. "
meta_image: "cover.png" # should exist in `app/assets/images/`
